workflows:
  sample-workflow:
    name: Sample Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_VERSION: 16

    scripts:
      - name: Install Dependencies
        script: yarn install

      - name: Build iOS App
        script: |
          npx expo install expo-constants
          eas build --platform ios --non-interactive --profile preview

    artifacts:
      - dist/*.ipa
