workflows:
  sample-workflow:
    name: Simple React Native Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_VERSION: 16

    scripts:
      - name: Install Dependencies
        script: yarn install

      - name: Build iOS App
        script: |
          cd ios
          pod install
          xcodebuild -workspace ViroStarterKit.xcworkspace -scheme ViroStarterKit -configuration Release -sdk iphoneos -archivePath build/ViroStarterKit.xcarchive archive
          xcodebuild -exportArchive -archivePath build/ViroStarterKit.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build

    artifacts:
      - build/*.ipa
